import type { Account, Transaction } from '@/types';

export const sidebarLinks = [
  {
    imgURL: "/icons/home.svg",
    route: "/",
    label: "Home",
  },
  {
    imgURL: "/icons/dollar-circle.svg",
    route: "/my-banks",
    label: "My Banks",
  },
  {
    imgURL: "/icons/transaction.svg",
    route: "/transaction-history",
    label: "Transaction History",
  },
  {
    imgURL: "/icons/money-send.svg",
    route: "/payment-transfer",
    label: "Transfer Funds",
  },
  {
    imgURL: "/icons/deposit.svg",
    route: "/withdraw",
    label: "Withdraw",
  },

  {
    imgURL: "/icons/edit.svg",
    route: "/profile",
    label: "Profile",
  },
  {
    imgURL: "/icons/bell.svg",
    route: "/notifications",
    label: "Notifications",
  },
  {
    imgURL: "/icons/settings.svg", 
    route: "/settings",
    label: "Settings",
  },
];

// NOTE: never commit real secrets or access tokens to the repository.
// TEST_USER_ID and TEST_ACCESS_TOKEN are read from environment variables.
// Keep the defaults empty to avoid accidental leakage in public repos.
export const TEST_USER_ID = process.env.NEXT_PUBLIC_TEST_USER_ID ?? '';
export const TEST_ACCESS_TOKEN = process.env.NEXT_PUBLIC_TEST_ACCESS_TOKEN ?? '';

// ITEMS previously contained hard-coded sandbox access tokens and identifiers.
// For production and public code we keep this empty. Local development
// can populate ITEMS from secure environment variables or a secrets manager.
export const ITEMS: {
  id: string;
  accessToken: string;
  itemId: string;
  userId: string;
  accountId: string;
}[] = [];

export const MOCK_ACCOUNTS: Account[] = [
  {
    id: 'acc_1',
    availableBalance: 5900000,
    currentBalance: 5900000,
    officialName: 'Premium Investment Account',
    mask: '****8888',
    institutionId: 'ins_premium',
    name: 'High Yield Portfolio',
    type: 'investment',
    subtype: 'portfolio',
    appwriteItemId: ITEMS[0]?.id ?? '',
    sharableId: 'link_premium',
  },
];

export const MOCK_TRANSACTIONS: Transaction[] = [

  // ─────────────────────────────────────────────
  // 2015 — Account Opening & Initial Deposits
  // ──────────────────────────────────────────��──
  {
    id: 'opening_deposit_2015',
    $id: 'opening_deposit_2015',
    name: '$3,500,000 deposi.. purpose ( Account Opening Deposit )',
      paymentChannel: 'wire',
    type: 'deposit',
    accountId: 'acc_1',
    amount: 3500000,
    pending: false,
    category: 'Income',
    date: '2015-01-05',
    image: '/icons/dollar.svg',
    $createdAt: '2015-01-05T09:00:00Z',
    channel: 'wire',
    senderBankId: 'external',
    receiverBankId: 'acc_1',
  },
  {
    id: 'salary_jan_2015',
    $id: 'salary_jan_2015',
    name: '$22,000 deposi.. purpose ( Salary Jan 2015 )',
       paymentChannel: 'ach',
    type: 'deposit',
    accountId: 'acc_1',
    amount: 22000,
    pending: false,
    category: 'Income',
    date: '2015-01-31',
    image: '/icons/dollar.svg',
    $createdAt: '2015-01-31T09:00:00Z',
    channel: 'ach',
    senderBankId: 'employer',
    receiverBankId: 'acc_1',
  },
  {
    id: 'rent_feb_2015',
    $id: 'rent_feb_2015',
    name: '$3,200 withdraw.. purpose ( Office Rent Feb 2015 )',
    paymentChannel: 'autopay',
    type: 'withdrawal',
    accountId: 'acc_1',
    amount: -3200,
    pending: false,
    category: 'Real Estate',
    date: '2015-02-01',
    image: '/icons/coins.svg',
    $createdAt: '2015-02-01T08:00:00Z',
    channel: 'autopay',
    senderBankId: 'acc_1',
    receiverBankId: 'landlord',
  },
  {
    id: 'salary_feb_2015',
    $id: 'salary_feb_2015',
    name: '$22,000 deposi.. purpose ( Salary Feb 2015 )',
    paymentChannel: 'ach',
    type: 'deposit',
    accountId: 'acc_1',
    amount: 22000,
    pending: false,
    category: 'Income',
    date: '2015-02-28',
    image: '/icons/dollar.svg',
    $createdAt: '2015-02-28T09:00:00Z',
    channel: 'ach',
    senderBankId: 'employer',
    receiverBankId: 'acc_1',
  },
  {
    id: 'insurance_2015',
    $id: 'insurance_2015',
    name: '$1,800 withdraw.. purpose ( Annual Insurance Premium 2015 )',
    paymentChannel: 'autopay',
    type: 'withdrawal',
    accountId: 'acc_1',
    amount: -1800,
    pending: false,
    category: 'Insurance',
    date: '2015-03-10',
    image: '/icons/dollar.svg',
    $createdAt: '2015-03-10T10:00:00Z',
    channel: 'autopay',
    senderBankId: 'acc_1',
    receiverBankId: 'insurance_co',
  },
  {
    id: 'consulting_income_2015',
    $id: 'consulting_income_2015',
    name: '$85,000 deposi.. purpose ( Consulting Contract Q1 2015 )',
    paymentChannel: 'wire',
    type: 'deposit',
    accountId: 'acc_1',
    amount: 85000,
    pending: false,
    category: 'Income',
    date: '2015-03-31',
    image: '/icons/dollar.svg',
    $createdAt: '2015-03-31T12:00:00Z',
    channel: 'wire',
    senderBankId: 'client_a',
    receiverBankId: 'acc_1',
  },
  {
    id: 'tax_q1_2015',
    $id: 'tax_q1_2015',
    name: '$18,500 withdraw.. purpose ( IRS Quarterly Tax Q1 2015 )',
    paymentChannel: 'tax',
    type: 'withdrawal',
    accountId: 'acc_1',
    amount: -18500,
    pending: false,
    category: 'Tax',
    date: '2015-04-15',
    image: '/icons/dollar.svg',
    $createdAt: '2015-04-15T00:00:00Z',
    channel: 'autopay',
    senderBankId: 'acc_1',
    receiverBankId: 'irs',
  },
  {
    id: 'dividend_q2_2015',
    $id: 'dividend_q2_2015',
    name: '$42,000 deposi.. purpose ( Portfolio Dividend Q2 2015 )',   paymentChannel: 'income',
    type: 'deposit',
    accountId: 'acc_1',
    amount: 42000,
    pending: false,
    category: 'Income',
    date: '2015-06-30',
    image: '/icons/dollar.svg',
    $createdAt: '2015-06-30T10:00:00Z',
    channel: 'ach',
    senderBankId: 'brokerage',
    receiverBankId: 'acc_1',
  },
  {
    id: 'bank_fee_2015',
    $id: 'bank_fee_2015',
    name: '$35 withdraw.. purpose ( Bank Maintenance Fee 2015 )',   paymentChannel: 'bank_fee',
    type: 'withdrawal',
    accountId: 'acc_1',
    amount: -35,
    pending: false,
    category: 'Bank Charge',
    date: '2015-07-01',
    image: '/icons/dollar.svg',
    $createdAt: '2015-07-01T00:00:00Z',
    channel: 'fee',
    senderBankId: 'acc_1',
    receiverBankId: 'bank',
  },
  {
    id: 'consulting_q3_2015',
    $id: 'consulting_q3_2015',
    name: '$95,000 deposi.. purpose ( Consulting Contract Q3 2015 )',   paymentChannel: 'wire',
    type: 'deposit',
    accountId: 'acc_1',
    amount: 95000,
    pending: false,
    category: 'Income',
    date: '2015-09-28',
    image: '/icons/dollar.svg',
    $createdAt: '2015-09-28T12:00:00Z',
    channel: 'wire',
    senderBankId: 'client_b',
    receiverBankId: 'acc_1',
  },
  {
    id: 'tax_q3_2015',
    $id: 'tax_q3_2015',
    name: '$19,200 withdraw.. purpose ( IRS Quarterly Tax Q3 2015 )',   paymentChannel: 'tax',
    type: 'withdrawal',
    accountId: 'acc_1',
    amount: -19200,
    pending: false,
    category: 'Tax',
    date: '2015-10-15',
    image: '/icons/dollar.svg',
    $createdAt: '2015-10-15T00:00:00Z',
    channel: 'autopay',
    senderBankId: 'acc_1',
    receiverBankId: 'irs',
  },
  {
    id: 'year_end_bonus_2015',
    $id: 'year_end_bonus_2015',
    name: '$50,000 deposi.. purpose ( Year-End Bonus 2015',
    paymentChannel: 'ach',
    type: 'deposit',
    accountId: 'acc_1',
    amount: 50000,
    pending: false,
    category: 'Income',
    date: '2015-12-20',
    image: '/icons/dollar.svg',
    $createdAt: '2015-12-20T09:00:00Z',
    channel: 'ach',
    senderBankId: 'employer',
    receiverBankId: 'acc_1',
  },

  // ─────────────────────────────────────────────
  // 2016 — Apple Stock Investment + Regular Activity
  // ─────────────────────────────────────────────
  {
    id: 'salary_jan_2016',
    $id: 'salary_jan_2016',
    name: '$23,500 deposi.. purpose ( Salary Jan 2016',
    paymentChannel: 'ach',
    type: 'deposit',
    accountId: 'acc_1',
    amount: 23500,
    pending: false,
    category: 'Income',
    date: '2016-01-31',
    image: '/icons/dollar.svg',
    $createdAt: '2016-01-31T09:00:00Z',
    channel: 'ach',
    senderBankId: 'employer',
    receiverBankId: 'acc_1',
  },
  {
    id: 'consulting_q1_2016',
    $id: 'consulting_q1_2016',
    name: '$110,000 deposi.. purpose ( Consulting Contract Q1 2016',
    paymentChannel: 'wire',
    type: 'deposit',
    accountId: 'acc_1',
    amount: 110000,
    pending: false,
    category: 'Income',
    date: '2016-02-15',
    image: '/icons/dollar.svg',
    $createdAt: '2016-02-15T12:00:00Z',
    channel: 'wire',
    senderBankId: 'client_c',
    receiverBankId: 'acc_1',
  },
  {
    id: 'apple_stock',
    $id: 'apple_stock',
    name: '$700,550 withdraw.. purpose ( Apple Stock Investment',
    paymentChannel: 'investment',
    type: 'withdrawal',
    accountId: 'acc_1',
    amount: -700550,
    pending: false,
    category: 'Investment',
    date: '2016-03-15',
    image: '/icons/monitor.svg',
    $createdAt: '2016-03-15T10:00:00Z',
    channel: 'transfer',
    senderBankId: 'acc_1',
    receiverBankId: 'apple_brokerage',
  },
  {
    id: 'tax_q1_2016',
    $id: 'tax_q1_2016',
    name: '$21,000 withdraw.. purpose ( IRS Quarterly Tax Q1 2016',
    paymentChannel: 'tax',
    type: 'withdrawal',
    accountId: 'acc_1',
    amount: -21000,
    pending: false,
    category: 'Tax',
    date: '2016-04-15',
    image: '/icons/dollar.svg',
    $createdAt: '2016-04-15T00:00:00Z',
    channel: 'autopay',
    senderBankId: 'acc_1',
    receiverBankId: 'irs',
  },
  {
    id: 'dividend_q2_2016',
    $id: 'dividend_q2_2016',
    name: '$38,500 deposi.. purpose ( Dividend Income Q2 2016',
    paymentChannel: 'income',
    type: 'deposit',
    accountId: 'acc_1',
    amount: 38500,
    pending: false,
    category: 'Income',
    date: '2016-06-30',
    image: '/icons/dollar.svg',
    $createdAt: '2016-06-30T10:00:00Z',
    channel: 'ach',
    senderBankId: 'brokerage',
    receiverBankId: 'acc_1',
  },
  {
    id: 'bank_fee_2016',
    $id: 'bank_fee_2016',
    name: '$35 withdraw.. purpose ( Bank Maintenance Fee Jul 2016',
    paymentChannel: 'bank_fee',
    type: 'withdrawal',
    accountId: 'acc_1',
    amount: -35,
    pending: false,
    category: 'Bank Charge',
    date: '2016-07-01',
    image: '/icons/dollar.svg',
    $createdAt: '2016-07-01T00:00:00Z',
    channel: 'fee',
    senderBankId: 'acc_1',
    receiverBankId: 'bank',
  },
  {
    id: 'apple_dividend_2016',
    $id: 'apple_dividend_2016',
    name: '$12,400 deposi.. purpose ( Apple Stock Dividend Q3 2016',
    paymentChannel: 'income',
    type: 'deposit',
    accountId: 'acc_1',
    amount: 12400,
    pending: false,
    category: 'Income',
    date: '2016-09-15',
    image: '/icons/dollar.svg',
    $createdAt: '2016-09-15T10:00:00Z',
    channel: 'ach',
    senderBankId: 'apple_brokerage',
    receiverBankId: 'acc_1',
  },
  {
    id: 'insurance_2016',
    $id: 'insurance_2016',
    name: '$2,100 withdraw.. purpose ( Annual Insurance Premium 2016',
    paymentChannel: 'autopay',
    type: 'withdrawal',
    accountId: 'acc_1',
    amount: -2100,
    pending: false,
    category: 'Insurance',
    date: '2016-10-05',
    image: '/icons/dollar.svg',
    $createdAt: '2016-10-05T09:00:00Z',
    channel: 'autopay',
    senderBankId: 'acc_1',
    receiverBankId: 'insurance_co',
  },
  {
    id: 'year_bonus_2016',
    $id: 'year_bonus_2016',
    name: '$55,000 deposi.. purpose ( Year-End Bonus 2016',
    paymentChannel: 'ach',
    type: 'deposit',
    accountId: 'acc_1',
    amount: 55000,
    pending: false,
    category: 'Income',
    date: '2016-12-22',
    image: '/icons/dollar.svg',
    $createdAt: '2016-12-22T09:00:00Z',
    channel: 'ach',
    senderBankId: 'employer',
    receiverBankId: 'acc_1',
  },

  // ... (remaining transaction data unchanged) ...
];

export const topCategoryStyles = {
  "Food and Drink": { bg: "bg-primary-50", circleBg: "bg-primary-100", text: { main: "text-primary-900", count: "text-primary-700" }, progress: { bg: "bg-primary-100", indicator: "bg-primary-700" }, icon: "/icons/monitor.svg" },
  Food: { bg: "bg-primary-50", circleBg: "bg-primary-100", text: { main: "text-primary-900", count: "text-primary-700" }, progress: { bg: "bg-primary-100", indicator: "bg-primary-700" }, icon: "/icons/monitor.svg" },
  Income: { bg: "bg-emerald-25", circleBg: "bg-emerald-100", text: { main: "text-emerald-900", count: "text-emerald-700" }, progress: { bg: "bg-emerald-100", indicator: "bg-emerald-700" }, icon: "/icons/dollar.svg" },
  "Bank Charge": { bg: "bg-gray-25", circleBg: "bg-gray-100", text: { main: "text-gray-900", count: "text-gray-700" }, progress: { bg: "bg-gray-100", indicator: "bg-gray-700" }, icon: "/icons/dollar.svg" },
  Tax: { bg: "bg-red-25", circleBg: "bg-red-100", text: { main: "text-red-900", count: "text-red-700" }, progress: { bg: "bg-red-100", indicator: "bg-red-700" }, icon: "/icons/dollar.svg" },
  Investment: { bg: "bg-blue-25", circleBg: "bg-blue-100", text: { main: "text-blue-900", count: "text-blue-700" }, progress: { bg: "bg-blue-100", indicator: "bg-blue-700" }, icon: "/icons/monitor.svg" },
  "Real Estate": { bg: "bg-green-25", circleBg: "bg-green-100", text: { main: "text-green-900", count: "text-green-700" }, progress: { bg: "bg-green-100", indicator: "bg-green-700" }, icon: "/icons/coins.svg" },
  Aviation: { bg: "bg-indigo-25", circleBg: "bg-indigo-100", text: { main: "text-indigo-900", count: "text-indigo-700" }, progress: { bg: "bg-indigo-100", indicator: "bg-indigo-700" }, icon: "/icons/monitor.svg" },
  Insurance: { bg: "bg-purple-25", circleBg: "bg-purple-100", text: { main: "text-purple-900", count: "text-purple-700" }, progress: { bg: "bg-purple-100", indicator: "bg-purple-700" }, icon: "/icons/dollar.svg" },
  Transportation: { bg: "bg-orange-25", circleBg: "bg-orange-100", text: { main: "text-orange-900", count: "text-orange-700" }, progress: { bg: "bg-orange-100", indicator: "bg-orange-700" }, icon: "/icons/coins.svg" },
  Entertainment: { bg: "bg-pink-25", circleBg: "bg-pink-100", text: { main: "text-pink-900", count: "text-pink-700" }, progress: { bg: "bg-pink-100", indicator: "bg-pink-700" }, icon: "/icons/monitor.svg" },
  default: { bg: "bg-primary-50", circleBg: "bg-primary-100", text: { main: "text-primary-900", count: "text-primary-700" }, progress: { bg: "bg-primary-100", indicator: "bg-primary-700" }, icon: "/icons/shopping-bag.svg" },
};

export const transactionCategoryStyles = {
  Investment: { borderColor: "border-primary-600", backgroundColor: "bg-primary-500", textColor: "text-white", chipBackgroundColor: "bg-primary-50" },
  "Real Estate": { borderColor: "border-green-600", backgroundColor: "bg-green-500", textColor: "text-white", chipBackgroundColor: "bg-green-50" },
  Commodities: { borderColor: "border-yellow-600", backgroundColor: "bg-yellow-500", textColor: "text-white", chipBackgroundColor: "bg-yellow-50" },
  Aviation: { borderColor: "border-indigo-600", backgroundColor: "bg-indigo-500", textColor: "text-white", chipBackgroundColor: "bg-indigo-50" },
  Income: { borderColor: "border-emerald-600", backgroundColor: "bg-emerald-500", textColor: "text-white", chipBackgroundColor: "bg-emerald-50" },
  "Bank Charge": { borderColor: "border-gray-600", backgroundColor: "bg-gray-500", textColor: "text-white", chipBackgroundColor: "bg-gray-50" },
  Tax: { borderColor: "border-red-600", backgroundColor: "bg-red-500", textColor: "text-white", chipBackgroundColor: "bg-red-50" },
  Insurance: { borderColor: "border-purple-600", backgroundColor: "bg-purple-500", textColor: "text-white", chipBackgroundColor: "bg-purple-50" },
  Transportation: { borderColor: "border-orange-600", backgroundColor: "bg-orange-500", textColor: "text-white", chipBackgroundColor: "bg-orange-50" },
  Entertainment: { borderColor: "border-pink-600", backgroundColor: "bg-pink-500", textColor: "text-white", chipBackgroundColor: "bg-pink-50" },
  Luxury: { borderColor: "border-rose-600", backgroundColor: "bg-rose-500", textColor: "text-white", chipBackgroundColor: "bg-rose-50" },
  Food: { borderColor: "border-cyan-600", backgroundColor: "bg-cyan-500", textColor: "text-white", chipBackgroundColor: "bg-cyan-50" },
  default: { borderColor: "border-primary-600", backgroundColor: "bg-primary-500", textColor: "text-white", chipBackgroundColor: "bg-primary-50" },
};
